# Generated by Django 6.0.3 on 2026-04-17 12:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_householdmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HomeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('rent', 'Rent'), ('owner', 'Owner')], max_length=10)),
                ('house_image', models.ImageField(blank=True, null=True, upload_to='houses/')),
                ('building_type', models.CharField(choices=[('brick', 'Brick'), ('wood', 'Wood'), ('concrete', 'Concrete'), ('mixed', 'Mixed')], max_length=10)),
                ('number_of_rooms', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('heating_type', models.CharField(choices=[('gas', 'Gas'), ('oil', 'Oil'), ('electric', 'Electric'), ('heat_pump', 'Heat Pump'), ('wood', 'Wood')], max_length=20)),
                ('heating_installation_year', models.IntegerField(blank=True, null=True)),
                ('floor_heating', models.BooleanField(default=False)),
                ('solar_panels', models.BooleanField(default=False)),
                ('solar_installation_year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='households.household')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household')),
                ('invited_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
