# Generated by Django 6.0.3 on 2026-06-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0003_household_created_at_household_owner_homeprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeprofile',
            name='number_of_rooms',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
