# Generated by Django 6.0.3 on 2026-04-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_bill_consumption_bill_created_by_user_bill_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='period_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='period_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
